import { motion, AnimatePresence } from 'framer-motion'
import { useStore } from '../../../../store'
import { MonoValue } from '../../../shared/MonoValue'

export function EvidencePendingPanel() {
  const pending = useStore((s) => s.evidencePending)

  return (
    <div className="flex flex-col h-full" style={{ backgroundColor: '#161310' }}>
      {/* Header */}
      <div
        className="shrink-0 px-3 py-2 flex items-center gap-2"
        style={{ borderBottom: '1px solid #2E2820', backgroundColor: '#161310' }}
      >
        <div style={{ width: '2px', height: '12px', backgroundColor: '#C8912A' }} />
        <span
          className="text-[9px] tracking-[0.2em]"
          style={{ fontFamily: 'Syne, sans-serif', fontWeight: 700, color: '#8C7A5E' }}
        >
          EVIDENCE PENDING
        </span>
        <span className="ml-auto text-[8px] font-mono" style={{ color: '#4A3D2A' }}>
          {pending.length} REQUESTS
        </span>
      </div>

      {/* Explanation */}
      <div className="shrink-0 px-3 py-2" style={{ borderBottom: '1px solid #2E2820', backgroundColor: '#0C0A07' }}>
        <p className="text-[8px] font-mono leading-relaxed" style={{ color: '#4A3D2A' }}>
          Evidence requests generated by the investigator to test surviving hypotheses. Shows what data would
          confirm or contradict the current theories.
        </p>
      </div>

      {/* Pending requests list */}
      <div className="flex-1 overflow-y-auto">
        <AnimatePresence mode="popLayout" initial={false}>
          {pending.map((item, idx) => (
            <motion.div
              key={`${item.requestedInCycle}-${item.description.slice(0, 30)}`}
              layout
              initial={{ x: 24, opacity: 0 }}
              animate={{ x: 0, opacity: 1 }}
              transition={{ duration: 0.3, ease: 'easeOut' }}
              style={{
                borderBottom: '1px solid #2E2820',
                borderLeft: '2px solid #C8912A',
                backgroundColor: '#161310',
              }}
            >
              <div className="px-3 py-3">
                {/* Header: type + cycle */}
                <div className="flex items-center gap-2 mb-2">
                  <span
                    className="text-[8px] font-mono px-1.5 py-0.5"
                    style={{
                      backgroundColor: item.type === 'structural' ? '#1A2D24' : '#2A1A09',
                      border:
                        item.type === 'structural'
                          ? '1px solid #2E9E7230'
                          : '1px solid #C8912A30',
                      color: item.type === 'structural' ? '#2E9E72' : '#C8912A',
                    }}
                  >
                    {item.type.toUpperCase()}
                  </span>
                  <MonoValue color="#4A3D2A" size="xs">
                    REQUESTED C{item.requestedInCycle}
                  </MonoValue>
                </div>

                {/* Description */}
                <p className="text-[9px] font-mono leading-relaxed mb-2" style={{ color: '#8C7A5E' }}>
                  {item.description}
                </p>

                {/* Reasoning */}
                {item.requestedBecause && (
                  <div
                    className="px-2 py-1.5 mt-2"
                    style={{
                      backgroundColor: '#0C0A07',
                      border: '1px solid #2E2820',
                    }}
                  >
                    <div className="flex items-center gap-1.5 mb-1">
                      <span className="text-[7px] font-mono tracking-wider" style={{ color: '#4A3D2A' }}>
                        REASON:
                      </span>
                    </div>
                    <p className="text-[8px] font-mono leading-relaxed" style={{ color: '#555555' }}>
                      {item.requestedBecause}
                    </p>
                  </div>
                )}
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {pending.length === 0 && (
          <div className="flex flex-col items-center justify-center h-32 gap-2 px-4">
            <span className="text-[9px] font-mono tracking-wider" style={{ color: '#4A3D2A' }}>
              NO PENDING EVIDENCE REQUESTS
            </span>
            <p className="text-[8px] font-mono text-center leading-relaxed" style={{ color: '#333333' }}>
              Investigator has all needed evidence or investigation is not yet active
            </p>
          </div>
        )}
      </div>
    </div>
  )
}
